version: '3'
services: 
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    env_file: .env
    environment:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongoUser.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - ./database/mongoDB:/data/db
    ports:
      - '27017:27017'
  api:
    env_file: .env
    build:
      dockerfile: Dockerfile
      context: ./api
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    depends_on:
      - mongo
      - api
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
